### ISSUE TITLE
Add fish tracker transmissions

### ISSUE THREAD

**Issue by SSModelGit** [Project-CETI/whale-tag-recovery#3]
Goal is to have it add fish tracking capabilities without the need for a physical fish tracker module, letting us do recovery even when the board cannot acquire GPS for APRS-based recovery.

Feature goals:
- [ ] Use the standard fish tracking frequency, 148.056MHz
- [ ] Have it happen at a configurable rate, ex. once a second for a minute, every ten minutes
- [ ] Configure to use the lowest power settings possible on the DRA818V

**Comment by SSModelGit** [comment]
- [ ] Use the standard fish tracking frequency, 148.056MHz
